### PR TITLE
Handle canceled events for HttpRequest and aborted events for HttpDependency

### LINKED ISSUE #550: AI doesn't _seem_ to properly honor the response 'aborted' event
Hello,

We're seeing some intermittent issues from one of our dependencies.
It's reported as an exception in LogAnalytics by [@hapijs/wreck](https://github.com/hapijs/wreck) that complains that "Payload stream closed prematurely".

- Googling around (eg. https://github.com/nodejs/node/issues/18756) seems to indicate
that `aborted` is emitted when the socket is prematurely closed.

However, the dependency is reported as a successful call by AI. Which is... well... surprising ;-)

- https://nodejs.org/api/http.html#http_class_http_clientrequest states that _"Unlike the request object, if the response closes prematurely, the response object does not emit an 'error' event but instead emits the 'aborted' event."_

It's entirely possible that I'm reading the code wrong, but I can't find any place where the code subscribes to that event.

Thoughts?

https://github.com/microsoft/ApplicationInsights-node.js/blob/c8fa5b8de5c34a4f50f64fa904aaaa8aa8002fae/AutoCollection/HttpDependencies.ts#L182-L206

### LINKED ISSUE #741: Log cancelled requests
Hi team,
recently I noticed that requests that have been canceled are not logged. 
I would like to have logs of canceled requests or at least have a possibility to enable them. 
Please correct me if this is currently possible, however I dug deeper with debugger and I noticed that currently application insights plugin is biding to two response events:
```
telemetry.response.once("finish", function () { ...
```
and
```
telemetry.request.on("error", function (error) {
```

while in my case canceled requests were visible only for `close` event.
not sure if relevant, but in a project where I tested it, API is based on hapi framework in version 19.2.0

### PR DESCRIPTION
**Pull request by xiao-lix**
Resolves #550 
Resolves #741

### CODE REVIEW

File: AutoCollection/HttpDependencyParser.ts [hunk 1]
```diff
@@ -42,6 +42,13 @@ class HttpDependencyParser extends RequestParser {
         this.correlationId = Util.getCorrelationContextTarget(response, RequestResponseHeaders.requestContextTargetKey);
     }
 
+    /**
+     * Called when the ClientRequest emits an abort event.
+     */
+     public onAbort() {
+        this._setStatus(undefined, undefined);
```
Comment (hectorhdzg) [inline AutoCollection/HttpDependencyParser.ts:49]: You can use onError and send an empty error, it will generate the same status

File: AutoCollection/HttpRequests.ts [hunk 2]
```diff
@@ -224,17 +224,30 @@ class AutoCollectHttpRequests {
             (<PrivateCustomProperties>correlationContext.customProperties).addHeaderData(requestParser.getCorrelationContextHeader());
         }
 
+        let isRequestEnd = false;
         // response listeners
         if (telemetry.response.once) {
             telemetry.response.once("finish", () => {
                 AutoCollectHttpRequests.endRequest(client, requestParser, telemetry, null, null);
+                isRequestEnd = true;
```
Comment (hectorhdzg) [inline AutoCollection/HttpRequests.ts:232]: isRequestFinished so it aligns with the Http event

**Review by hectorhdzg — APPROVED** [review]
