### PR TITLE
Add Support for Tracking Shim Usage in Statsbeat & Fix Proxy Settings Issue

### LINKED ISSUE #1329: [BUG] Custom proxy with error "Expecting a valid host string in proxy settings, but found"
**Description/Screenshot**
In my company we have set a corporate proxy. To connect to Internet the application has to use this proxy.
The proxy has the format of "http://proxy.companyname.i:port". 
I have set that proxy over env variable http_proxy und https_proxy. Currently I receive this error

> Configuring Azure AppInsights
Failed to start default client: [object Error]{ stack: 'Error: Expecting a valid host string in proxy settings, but found "proxy.companyname.i".
2024-05-15T13:03:52.037201912Z     at getUrlFromProxySettings (/app/node_modules/@azure/core-rest-pipeline/dist/commonjs/policies/proxyPolicy.js:129:15)
    at proxyPolicy (/app/node_modules/@azure/core-rest-pipeline/dist/commonjs/policies/proxyPolicy.js:177:11)
2024-05-15T13:03:52.037210399Z     at createPipelineFromOptions (/app/node_modules/@azure/core-rest-pipeline/dist/commonjs/createPipelineFromOptions.js:30:61)
    at createClientPipeline (/app/node_modules/@azure/core-client/dist/commonjs/pipeline.js:16:73)
    at createDefaultPipeline (/app/node_modules/@azure/core-client/dist/commonjs/serviceClient.js:157:51)
    at new ServiceClient (/app/node_modules/@azure/core-client/dist/commonjs/serviceClient.js:53:45)
    at new ApplicationInsightsClient (/app/node_modules/@azure/monitor-opentelemetry-exporter/dist/index.js:1824:9)
2024-05-15T13:03:52.037227236Z     at new HttpSender (/app/node_modules/@azure/monitor-opentelemetry-exporter/dist/index.js:2782:34)
    at new AzureMonitorMetricExporter (/app/node_modules/@azure/monitor-opentelemetry-exporter/dist/index.js:3591:24)
    at new MetricHandler (/app/node_modules/@azure/monitor-opentelemetry/dist/index.js:3220:31)', message: 'Expecting a valid host string in proxy settings, but found "proxy.companyname.i".', name: 'Error' []
AppInsights ProxyHttpUrl: http://proxy.companyname.i:port
AppInsights new ProxyHttpUrl: http://proxy.companyname.i:port
`

**Steps to Reproduce**
 - SDK Version [e.g. 22]: 3.0.0
 - How you initialized the SDK:

> if (process.env.APPLICATIONINSIGHTS_CONNECTION_STRING) {
    console.log('Configuring Azure AppInsights');
    appInsights
      .setup(process.env.APPLICATIONINSIGHTS_CONNECTION_STRING)
      .setAutoDependencyCorrelation(false)
      .setAutoCollectRequests(true)
      .setAutoCollectPerformance(false, false)
      .setAutoCollectExceptions(true)
      .setAutoCollectDependencies(false)
      .setAutoCollectConsole(false)
      .start();
  }

**Expected behavior**
What should I have to do to tell ApplicationInsights SDK that "proxy.companayname.i:port" is a valid host?

### PR DESCRIPTION
**Pull request by JacksonWeber**
* Adds support for tracking usage of the Application Insights 3.X SDK in statsbeat.
* Removes setting config properties in the event that proxies are passed in from env vars. In these cases the core-pipeline reads the env var directly, so it doesn't require parsing on our side. Resolves #1329

### CODE REVIEW

File: src/main.ts [hunk 1]
```diff
@@ -28,6 +29,10 @@ let perfCounters: PerformanceCounterMetrics;
  * @param options Configuration
  */
 export function useAzureMonitor(options?: AzureMonitorOpenTelemetryOptions) {
+    process.env[AZURE_MONITOR_STATSBEAT_FEATURES] = JSON.stringify({
```
Comment (hectorhdzg) [inline src/main.ts:32]: I would assume some the statbeat features are actually set after the configuration is done right? are you not missing that here?

Comment (JacksonWeber) [reply src/main.ts:32]: We don't currently set any other statsbeat features from the shim, but setting this after initializing our config avoids the possibility of a future bug. I'll move this.

Comment (hectorhdzg) [reply src/main.ts:32]: We discussed this need to be there because Distro need to have this before initialization. Please add comment so we don't forget in the future

**Review by hectorhdzg — APPROVED** [review]
LGTM
