### PR TITLE
parse nonstring request-context header

### LINKED ISSUE #512: Uncaught exception: TypeError: correlationHeader.split is not a function
Nodes `getHeader` function can return various different types but this library assumes that it always return a string, and crashes for a certain request in my application:

```
TypeError: correlationHeader.split is not a function
    at Function.AutoCollectHttpDependencies.trackRequest (D:\home\site\wwwroot\node_modules\applicationinsights\out\AutoCollection\HttpDependencies.js:115:56)
    at clientRequestPatch (D:\home\site\wwwroot\node_modules\applicationinsights\out\AutoCollection\HttpDependencies.js:45:45)
    at https.request (D:\home\site\wwwroot\node_modules\applicationinsights\out\AutoCollection\HttpDependencies.js:67:13)
    at D:\home\site\wwwroot\node_modules\node-fetch\lib\index.js:1421:15
    at new Promise (<anonymous>)
    at fetch (D:\home\site\wwwroot\node_modules\node-fetch\lib\index.js:1390:9)
    at _callee$ (D:\home\site\wwwroot\build\lib\call.js:114:71)
    at tryCatch (D:\home\site\wwwroot\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\home\site\wwwroot\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (D:\home\site\wwwroot\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:114:21)
Debug: internal, implementation, error 
    TypeError: correlationHeader.split is not a function
    at Function.AutoCollectHttpDependencies.trackRequest (D:\home\site\wwwroot\node_modules\applicationinsights\out\AutoCollection\HttpDependencies.js:115:56)
    at clientRequestPatch (D:\home\site\wwwroot\node_modules\applicationinsights\out\AutoCollection\HttpDependencies.js:45:45)
    at https.request (D:\home\site\wwwroot\node_modules\applicationinsights\out\AutoCollection\HttpDependencies.js:67:13)
    at D:\home\site\wwwroot\node_modules\node-fetch\lib\index.js:1421:15
    at new Promise (<anonymous>)
    at fetch (D:\home\site\wwwroot\node_modules\node-fetch\lib\index.js:1390:9)
    at _callee$ (D:\home\site\wwwroot\build\lib\call.js:114:71)
    at tryCatch (D:\home\site\wwwroot\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (D:\home\site\wwwroot\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (D:\home\site\wwwroot\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:114:21)
```

### PR DESCRIPTION
**Pull request by markwolff**
Fixes #512 

`getHeader` returns a type of `any` instead of `string`. Only occurrence of this in the SDK is with `request-context` parsing. This PR attempts to parse `request-context` header for `<string | string[] | number>`, else it fallsback to `toString`. Current node typings dev dependency of this SDK has the type as returning a string, so it may be useful to upgrade to a more recent typings version for SDK development.

### CODE REVIEW

File: AutoCollection/HttpDependencies.ts [hunk 1]
```diff
@@ -122,31 +122,33 @@ class AutoCollectHttpDependencies {
...
-                    }
+                // getHeader returns "any" type in newer versions of node. In basic scenarios, this will be <string | string[] | number>, but could be modified to anything else via middleware
+                const correlationHeader = <any>telemetry.request.getHeader(RequestResponseHeaders.requestContextHeader)
+                if (typeof correlationHeader === "string") {
+                    AutoCollectHttpDependencies.addRequestCorrelationIdHeaderFromString(client, telemetry, correlationHeader)
+                } else if (correlationHeader instanceof Array) { // string[]
+                    const headers = correlationHeader.join(",");
+                    AutoCollectHttpDependencies.addRequestCorrelationIdHeaderFromString(client, telemetry, headers)
+                } else if (correlationHeader && typeof (correlationHeader as any).toString === "function") {
+                    // best effort attempt: requires well-defined toString
```
Comment (ramthi) [inline AutoCollection/HttpDependencies.ts]: AutoCollectHttpDependencies.addRequestCorrelationIdHeaderFromString(..) is being called multiple times in this block.  Try to set a single header string for various cases and just call AutoCollectHttpDependencies.addRequestCorrelationIdHeaderFromString(..) once with the header value.

File: AutoCollection/HttpRequests.ts [hunk 2]
```diff
@@ -232,21 +232,33 @@ class AutoCollectHttpRequests {
...
-                }
+            const correlationHeader = <any>response.getHeader(RequestResponseHeaders.requestContextHeader);
+            if (typeof correlationHeader === "string") {
+                AutoCollectHttpRequests.addResponseCorrelationIdHeaderFromString(client, response, correlationHeader)
+            } else if (correlationHeader instanceof Array) { // string[]
+                const headers = correlationHeader.join(",");
+                AutoCollectHttpRequests.addResponseCorrelationIdHeaderFromString(client, response, headers)
+            } else if (correlationHeader && typeof (correlationHeader as any).toString === "function") {
+                const header = (correlationHeader as any).toString();
+                AutoCollectHttpRequests.addResponseCorrelationIdHeaderFromString(client, response, header);
```
Comment (ramthi) [inline AutoCollection/HttpRequests.ts]: Same comments as in HttpDependencies.ts.  This could be refactored.

File: AutoCollection/HttpDependencies.ts [hunk 3]
```diff
@@ -122,31 +122,40 @@ class AutoCollectHttpDependencies {
...
+                const correlationHeader = <any>telemetry.request.getHeader(RequestResponseHeaders.requestContextHeader)
+                let header: string; // cast correlationHeader to string
+                if (typeof correlationHeader === "string") {
+                    header = correlationHeader;
+                } else if (correlationHeader instanceof Array) { // string[]
+                    header = correlationHeader.join(",");
+                } else if (correlationHeader && typeof (correlationHeader as any).toString === "function") {
+                    // best effort attempt: requires well-defined toString
+                    try {
+                        header = (correlationHeader as any).toString();
```
Comment (OsvaldoRosado) [inline AutoCollection/HttpDependencies.ts]: Do you know if there's any functional or performance differences between `header.toString()` and `'' + header` or `String(header)`?

File: AutoCollection/HttpDependencies.ts [hunk 4]
```diff
@@ -122,31 +122,40 @@ class AutoCollectHttpDependencies {
...
+                    } catch (err) {
+                        Logging.warn("Outgoing request-context header could not be parsed. Correlation of requests may be lost.", err, correlationHeader);
```
Comment (OsvaldoRosado) [inline AutoCollection/HttpDependencies.ts]: Do you think `parsed` might give users the false idea that we could read it but they sent headers in the wrong format?

File: AutoCollection/HttpDependencies.ts [hunk 5]
```diff
@@ -122,31 +122,40 @@ class AutoCollectHttpDependencies {
...
                 }
-            }
 
-            if (currentContext && currentContext.operation) {
-                telemetry.request.setHeader(RequestResponseHeaders.requestIdHeader, uniqueRequestId);
-                // Also set legacy headers
-                telemetry.request.setHeader(RequestResponseHeaders.parentIdHeader, currentContext.operation.id);
-                telemetry.request.setHeader(RequestResponseHeaders.rootIdHeader, uniqueRequestId);
+                if (currentContext && currentContext.operation) {
+                    telemetry.request.setHeader(RequestResponseHeaders.requestIdHeader, uniqueRequestId);
```
Comment (OsvaldoRosado) [inline AutoCollection/HttpDependencies.ts]: Don't these need try-catch?

File: AutoCollection/HttpDependencies.ts (hunk 4 above)
Comment (markwolff) [reply AutoCollection/HttpDependencies.ts]: I guess I am using parsed as read right now, but it does introduce ambiguity. "Read" is more correct as to why correlation will not be working

File: AutoCollection/HttpRequests.ts [hunk 6]
```diff
@@ -232,21 +232,40 @@ class AutoCollectHttpRequests {
...
-            if (correlationHeader) {
-                const components = correlationHeader.split(",");
-                const key = `${RequestResponseHeaders.requestContextSourceKey}=`;
-                if (!components.some((value) => value.substring(0,key.length) === key)) {
-                    response.setHeader(
-                        RequestResponseHeaders.requestContextHeader,
-                        `${correlationHeader},${RequestResponseHeaders.requestContextSourceKey}=${client.config.correlationId}`);
+            const correlationHeader = <any>response.getHeader(RequestResponseHeaders.requestContextHeader);
+            let header: string;
+            if (typeof correlationHeader === "string") { // string
```
Comment (OsvaldoRosado) [inline AutoCollection/HttpRequests.ts]: This "safe read" logic should probably be made a util since it's needed in two files

File: AutoCollection/HttpDependencies.ts (hunk 3 above)
Comment (markwolff) [reply AutoCollection/HttpDependencies.ts]: https://stackoverflow.com/questions/3945202/whats-the-difference-between-stringvalue-vs-value-tostring
It seems `'' + header` and `String(header)` are equivalent, and they attempt to call `toString` (and `valueOf` if that failed). For perf, it seems toString is slightly better, but using either of the other two would cover the scenario of `valueOf` being properly defined instead of `toString` for a custom object.

File: AutoCollection/HttpDependencies.ts (hunk 5 above)
Comment (markwolff) [reply AutoCollection/HttpDependencies.ts]: Added try/catch for setHeader group in outgoing requests
